name: protein_prediction_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - scikit-learn=1.6.1
  - pandas
  - torch=2.5.1
  - json
  - esm=2.0.0
  - huggingface_hub=0.29.3
